voutitle: "Dolores Valide"
logo: "/assets/20240801_112349-removebg-preview.png"
description: >
  La data est la valeur montante de cette décennie, et si je vous aidais à la valoriser?!
  Salut, je suis Dolores Valide une data scientist qui peut travailler sur des sujets de data science
  mais tout aussi bien sur des sujets de data analyse, business intelligence.
  Ici vous trouverez mon parcours et mes projets, je vous dévoile ma passion pour la data. 
show_downloads: true
theme: jekyll-theme-minimal
