title : Dolores Valide
#logo: 
description: Data Scientiste/Data Analyste avec une expertise de 2 ans, je cherche des missions longues durées prioritairement avec des déplacements ponctuels acceptés.
Spécialisé(e) dans l'analyse de données et le développement de modèles prédictifs, j'apporte des solutions data-driven pour améliorer la performance des entreprises.
Disponible immédiatement, je propose mes services à un taux journalier de 350€ minimum. Passionnée et motivée, curieuse je suis prête à relever de nouveaux défis et à apporter une réelle valeur ajoutée à vos projets.
Collaborez avec moi et vous ne le regretterez pas !
show_downloads: true
theme: jekill-theme-minimal
